# -*- coding: utf-8 -*-
from . import ir_ui_view
from . import is_param_project
from . import is_mold
from . import is_dossierf
from . import is_doc_moule
from . import dhtmlxgantt_project
from . import is_revue_de_contrat
from . import is_revue_lancement
from . import is_dossier_modif_variante
from . import is_revue_projet_jalon
from . import is_revue_risque
from . import is_dossier_appel_offre
from . import is_fermeture_gantt
from . import is_mold_project
from . import is_gantt_pdf
from . import is_gantt_copie
from . import ir_attachment
from . import is_modele_bilan
from . import suivi_projet
from . import is_creation_doc_migration
from . import is_dossier_article
from . import is_indicateur_revue_jalon
from . import is_fiche_codification
from . import is_fiche_information_prospect
from . import is_modif_donnee_technique
from . import is_prise_avance
from . import is_demande_modif_compte_fournisseur
from . import is_demande_modif_tarif_fournisseur
from . import is_plan_action
from . import is_plan_amelioration_continu
from . import is_inv_achat_moule
from . import is_erd
from . import is_liste_diffusion_mail
